using System.Reflection;using Biblia.Application.Interfaces;using Biblia.Domain.Entities;using MigraDoc.DocumentObjectModel;using MigraDoc.Rendering;using PdfSharp.Fonts;using Font=MigraDoc.DocumentObjectModel.Font;using Colors=MigraDoc.DocumentObjectModel.Colors;
namespace Biblia.Infrastructure.Files;
public sealed class PdfService:IPdfService
{
 static readonly object FontLock=new();readonly IAppPaths paths;public PdfService(IAppPaths paths){this.paths=paths;EnsureFontResolver();}
 public Task<string> CreateThemeVersePdfAsync(ThemeVerseReport report,CancellationToken ct=default){ct.ThrowIfCancellationRequested();var dir=Path.Combine(paths.CacheDirectory,"exports");Directory.CreateDirectory(dir);var path=Path.Combine(dir,$"temas-versiculos-{report.GeneratedAt:yyyyMMdd-HHmmss}.pdf");var renderer=new PdfDocumentRenderer{Document=Build(report)};renderer.RenderDocument();ct.ThrowIfCancellationRequested();renderer.PdfDocument.Save(path);return Task.FromResult(path);}
 static Document Build(ThemeVerseReport report){var d=new Document{Info={Title=report.Title,Subject="Relatório de temas e versículos",Author="BíbliaTema"}};var normal=d.Styles[StyleNames.Normal]!;normal.Font.Name="Open Sans";normal.Font.Size=10.5;normal.Font.Color=C("#17212B");normal.ParagraphFormat.LineSpacing=1.15;var s=d.AddSection();s.PageSetup.PageFormat=PageFormat.A4;s.PageSetup.TopMargin=Unit.FromCentimeter(2.3);s.PageSetup.BottomMargin=Unit.FromCentimeter(2);s.PageSetup.LeftMargin=s.PageSetup.RightMargin=Unit.FromCentimeter(1.8);Header(s);Footer(s,report.GeneratedAt.Year);var eye=s.AddParagraph("RELATÓRIO TEMÁTICO");eye.Format.Font=new Font("Open Sans",9){Bold=true,Color=C("#1769AA")};var title=s.AddParagraph(report.Title);title.Format.Font=new Font("Open Sans",24){Bold=true,Color=C("#174F7D")};title.Format.SpaceAfter=Unit.FromPoint(8);var meta=s.AddParagraph($"Versão: {report.VersionLabel}\nGerado em: {report.GeneratedAt.ToLocalTime():dd/MM/yyyy HH:mm}\n{report.ThemeCount} tema(s) - {report.ReferenceCount} referência(s)");meta.Format.Font.Color=C("#667585");meta.Format.SpaceAfter=Unit.FromPoint(14);foreach(var group in report.Sections){var h=s.AddParagraph(group.Theme.Name);h.Format.Font=new Font("Open Sans",16){Bold=true,Color=C("#174F7D")};h.Format.SpaceBefore=Unit.FromPoint(14);h.Format.KeepWithNext=true;var rule=s.AddParagraph();rule.Format.Borders.Bottom.Color=C(Safe(group.Theme.ColorHex));rule.Format.Borders.Bottom.Width=Unit.FromPoint(1.5);rule.Format.KeepWithNext=true;if(group.References.Count==0){var empty=s.AddParagraph("Nenhum versículo vinculado a este tema.");empty.Format.Font.Italic=true;empty.Format.Font.Color=C("#667585");}foreach(var r in group.References){var rh=s.AddParagraph(r.FormattedReference);rh.Format.Font=new Font("Open Sans",10){Bold=true,Color=C("#1769AA")};rh.Format.KeepWithNext=true;rh.Format.SpaceBefore=Unit.FromPoint(8);s.AddParagraph(r.PassageText);if(!string.IsNullOrWhiteSpace(r.Observation)){var t=s.AddTable();t.AddColumn(Unit.FromCentimeter(16.2));var cell=t.AddRow().Cells[0];cell.Shading.Color=C("#FFF8E1");cell.Borders.Left.Color=C("#D4A017");cell.Borders.Left.Width=Unit.FromPoint(3);var n=cell.AddParagraph();n.AddFormattedText("Observação do vínculo\n",TextFormat.Bold);n.AddText(r.Observation);n.Format.Font.Size=9.5;}}}return d;}
 static void Header(Section s){var p=s.Headers.Primary.AddParagraph();p.AddFormattedText("BÍBLIATEMA",TextFormat.Bold);p.AddTab();p.AddText("Temas e versículos");p.Format.TabStops.AddTabStop(Unit.FromCentimeter(16.2),TabAlignment.Right);p.Format.Font=new Font("Open Sans",8.5){Color=Colors.White};p.Format.Shading.Color=C("#174F7D");}
 static void Footer(Section s,int year){var p=s.Footers.Primary.AddParagraph();p.AddText($"BíbliaTema - {year}");p.AddTab();p.AddText("Página ");p.AddPageField();p.AddText(" de ");p.AddNumPagesField();p.Format.TabStops.AddTabStop(Unit.FromCentimeter(16.2),TabAlignment.Right);p.Format.Font=new Font("Open Sans",8){Color=C("#667585")};p.Format.Borders.Top.Color=C("#DCE4EC");}
 static Color C(string hex)=>Color.Parse(hex);static string Safe(string? v)=>!string.IsNullOrWhiteSpace(v)&&v.Length==7&&v[0]=='#'&&v[1..].All(Uri.IsHexDigit)?v:"#1769AA";static void EnsureFontResolver(){lock(FontLock){if(GlobalFontSettings.FontResolver is null)GlobalFontSettings.FontResolver=new EmbeddedFontResolver();}}
}
internal sealed class EmbeddedFontResolver:IFontResolver{public FontResolverInfo? ResolveTypeface(string familyName,bool isBold,bool isItalic)=>new(isBold?"OpenSans-Semibold":"OpenSans-Regular");public byte[]? GetFont(string faceName){var resource=faceName=="OpenSans-Semibold"?"Biblia.Fonts.OpenSans-Semibold.ttf":"Biblia.Fonts.OpenSans-Regular.ttf";using var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream(resource)??throw new InvalidOperationException($"Fonte incorporada não encontrada: {resource}");using var memory=new MemoryStream();stream.CopyTo(memory);return memory.ToArray();}}
