using Biblia.Application.Interfaces.Repositories;
using Biblia.Domain.Entities;
using Biblia.Domain.Enums;
using Microsoft.Data.Sqlite;

namespace Biblia.Infrastructure.Repositories;

public sealed class BibleVersionCatalogRepository : SqliteRepositoryBase,IBibleVersionCatalogRepository
{
    public BibleVersionCatalogRepository(Biblia.Infrastructure.AppDatabase.AppDatabase database):base(database){}
    public async Task<BibleVersionCatalogEntry> CreateAsync(BibleVersionCatalogEntry e,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText=InsertSql+" SELECT last_insert_rowid();";Bind(cmd,e,false);var id=Convert.ToInt64(await cmd.ExecuteScalarAsync(token));return e with{Id=id};}
    public async Task<BibleVersionCatalogEntry?> GetByCodeAsync(string code,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Code,DisplayName,Language,DatabaseFileName,InstalledPath,SchemaVersion,LicenseName,LicenseText,Attribution,IsInstalled,IsEnabled,IsBundled,InstalledAt,UpdatedAt,ValidationStatus,ValidationMessage FROM BibleVersionCatalog WHERE Code=$code;";cmd.Parameters.AddWithValue("$code",code);await using var r=await cmd.ExecuteReaderAsync(token);return await r.ReadAsync(token)?Map(r):null;}
    public async Task<IReadOnlyList<BibleVersionCatalogEntry>> GetAllAsync(CancellationToken token=default){var result=new List<BibleVersionCatalogEntry>();await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Code,DisplayName,Language,DatabaseFileName,InstalledPath,SchemaVersion,LicenseName,LicenseText,Attribution,IsInstalled,IsEnabled,IsBundled,InstalledAt,UpdatedAt,ValidationStatus,ValidationMessage FROM BibleVersionCatalog ORDER BY DisplayName COLLATE NOCASE;";await using var r=await cmd.ExecuteReaderAsync(token);while(await r.ReadAsync(token))result.Add(Map(r));return result;}
    public async Task UpdateAsync(BibleVersionCatalogEntry e,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE BibleVersionCatalog SET Code=$code,DisplayName=$name,Language=$language,DatabaseFileName=$file,InstalledPath=$path,SchemaVersion=$schema,LicenseName=$licenseName,LicenseText=$licenseText,Attribution=$attribution,IsInstalled=$installed,IsEnabled=$enabled,IsBundled=$bundled,InstalledAt=$installedAt,UpdatedAt=$updatedAt,ValidationStatus=$status,ValidationMessage=$message WHERE Id=$id;";Bind(cmd,e,true);if(await cmd.ExecuteNonQueryAsync(token)!=1)throw new KeyNotFoundException("Versão não encontrada.");}
    public async Task DeleteAsync(long id,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="DELETE FROM BibleVersionCatalog WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);await cmd.ExecuteNonQueryAsync(token);}
    private const string InsertSql="INSERT INTO BibleVersionCatalog(Code,DisplayName,Language,DatabaseFileName,InstalledPath,SchemaVersion,LicenseName,LicenseText,Attribution,IsInstalled,IsEnabled,IsBundled,InstalledAt,UpdatedAt,ValidationStatus,ValidationMessage) VALUES($code,$name,$language,$file,$path,$schema,$licenseName,$licenseText,$attribution,$installed,$enabled,$bundled,$installedAt,$updatedAt,$status,$message);";
    private static void Bind(SqliteCommand cmd,BibleVersionCatalogEntry e,bool includeId){cmd.Parameters.AddWithValue("$code",e.Code);cmd.Parameters.AddWithValue("$name",e.DisplayName);cmd.Parameters.AddWithValue("$language",e.Language);cmd.Parameters.AddWithValue("$file",e.DatabaseFileName);AddNullable(cmd.Parameters,"$path",e.InstalledPath);cmd.Parameters.AddWithValue("$schema",e.SchemaVersion);AddNullable(cmd.Parameters,"$licenseName",e.LicenseName);AddNullable(cmd.Parameters,"$licenseText",e.LicenseText);AddNullable(cmd.Parameters,"$attribution",e.Attribution);cmd.Parameters.AddWithValue("$installed",e.IsInstalled?1:0);cmd.Parameters.AddWithValue("$enabled",e.IsEnabled?1:0);cmd.Parameters.AddWithValue("$bundled",e.IsBundled?1:0);AddNullable(cmd.Parameters,"$installedAt",e.InstalledAt?.ToString("O"));AddNullable(cmd.Parameters,"$updatedAt",e.UpdatedAt?.ToString("O"));cmd.Parameters.AddWithValue("$status",(int)e.ValidationStatus);AddNullable(cmd.Parameters,"$message",e.ValidationMessage);if(includeId)cmd.Parameters.AddWithValue("$id",e.Id);}
    private static BibleVersionCatalogEntry Map(SqliteDataReader r)=>new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetInt32(6),r.IsDBNull(7)?null:r.GetString(7),r.IsDBNull(8)?null:r.GetString(8),r.IsDBNull(9)?null:r.GetString(9),r.GetInt32(10)!=0,r.GetInt32(11)!=0,r.GetInt32(12)!=0,ReadNullableDate(r,13),ReadNullableDate(r,14),(BibleVersionValidationStatus)r.GetInt32(15),r.IsDBNull(16)?null:r.GetString(16));
}
